package com.amfalmeida.mailhawk.service;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.microprofile.config.inject.ConfigProperty;

/**
 * Logs the application version (tag, commit and branch) at startup from the
 * git.properties file generated by the git-commit-id-maven-plugin.
 */
@Slf4j
@ApplicationScoped
@RequiredArgsConstructor(onConstructor_ = @Inject)
public final class ApplicationInfo {

    private static final String GIT_PROPERTIES_FILE = "git.properties";

    @ConfigProperty(name = "quarkus.application.version")
    String appVersion;

    void logVersion(@Observes final StartupEvent event) {
        final Properties git = loadGitProperties();
        if (git == null) {
            log.info("Mail Hawk version {} (git.properties not found)", appVersion);
            return;
        }
        log.info("Mail Hawk version {}", describeVersion(git));
    }

    String describeVersion(final Properties git) {
        final String tag = git.getProperty("git.closest.tag.name", "");
        final String describe = git.getProperty("git.commit.id.describe", "");
        final String version = firstNonEmpty(tag, describe, appVersion);
        final String tags = git.getProperty("git.tags", "");
        return String.format("%s (tags: %s, commit: %s, branch: %s)",
            version,
            tags.isEmpty() ? "none" : tags,
            git.getProperty("git.commit.id.abbrev", "unknown"),
            git.getProperty("git.branch", "unknown"));
    }

    private Properties loadGitProperties() {
        try (final InputStream in = getClass().getClassLoader().getResourceAsStream(GIT_PROPERTIES_FILE)) {
            if (in == null) {
                return null;
            }
            final Properties properties = new Properties();
            properties.load(in);
            return properties;
        } catch (final IOException e) {
            log.warn("Could not read {}: {}", GIT_PROPERTIES_FILE, e.getMessage());
            return null;
        }
    }

    private static String firstNonEmpty(final String first, final String second, final String fallback) {
        if (!first.isEmpty()) {
            return first;
        }
        return second.isEmpty() ? fallback : second;
    }
}
