-- V1__Initial_schema.sql
-- Create processed_invoices table
CREATE TABLE IF NOT EXISTS processed_invoices (
    raw_qr_hash TEXT PRIMARY KEY,
    atcud TEXT,
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    invoice_id TEXT,
    invoice_date TEXT,
    issuer_name TEXT,
    issuer_nif TEXT,
    customer_nif TEXT,
    customer_country TEXT,
    invoice_type TEXT,
    status TEXT,
    total REAL,
    total_taxes REAL,
    non_taxable REAL,
    stamp_duty REAL,
    withholding_tax REAL,
    hash TEXT,
    certificate_number TEXT,
    other_information TEXT,
    raw_qr TEXT,
    subject TEXT,
    from_email TEXT,
    from_name TEXT,
    to_email TEXT,
    tax_country_region TEXT,
    basics_exempt_taxes REAL,
    basics_reduced_rate REAL,
    total_taxes_reduced_rate REAL,
    basics_intermediate_rate REAL,
    total_taxes_intermediate_rate REAL,
    basics_standard_rate REAL,
    total_taxes_standard_rate REAL,
    tax_country_region_2 TEXT,
    basics_exempt_taxes_2 REAL,
    basics_reduced_rate_2 REAL,
    total_taxes_reduced_rate_2 REAL,
    basics_intermediate_rate_2 REAL,
    total_taxes_intermediate_rate_2 REAL,
    basics_standard_rate_2 REAL,
    total_taxes_standard_rate_2 REAL,
    tax_country_region_3 TEXT,
    basics_exempt_taxes_3 REAL,
    basics_reduced_rate_3 REAL,
    total_taxes_reduced_rate_3 REAL,
    basics_intermediate_rate_3 REAL,
    total_taxes_intermediate_rate_3 REAL,
    basics_standard_rate_3 REAL,
    total_taxes_standard_rate_3 REAL
);

-- Create invoice_configs table
CREATE TABLE IF NOT EXISTS invoice_configs (
    id TEXT PRIMARY KEY,
    type TEXT,
    from_email TEXT,
    name TEXT,
    nif TEXT
);
